Cloud bastion
Otus-DevOps-2019-11/dsmamontov_infra pull request #2
Opened 2019-12-21 15:57 UTC by dsmamontov

Добрый вечер!
Задание готово, только несовсем поднятно куда присылать дополнительные задания и надо ли?

Например, настройки аллиаса ssh

2019-12-22 19:55 UTC, mrgreyves requested changes
Здравствуйте! На момент тестирования сервер был в работе? Тесты не могут пройти так как нет соединения.

2019-12-22 19:55 UTC, mrgreyves commented on README.md
> +ssh -L 2222:10.128.0.2:22 OpenSSH-rsa-import-101417@35.230.101.179
Это имя пользователя такое?0_о

2019-12-22 19:57 UTC, dsmamontov commented on README.md
> +ssh -L 2222:10.128.0.2:22 OpenSSH-rsa-import-101417@35.230.101.179
Добрый вечер!
Да, как тесты прошли -- удалил вм. Могу поднять заново

Имя пользователя такое потому что гугл, как я понял, берет его из комментария к ssh ключу)

2019-12-22 19:58 UTC, mrgreyves commented on README.md
> +ssh -L 2222:10.128.0.2:22 OpenSSH-rsa-import-101417@35.230.101.179
Верно, из коммента) И посльзователь должен быть как в методичке то есть appuser.
Лучше провести тесты заново =)

2019-12-24 17:36 UTC, dsmamontov commented on README.md
> +ssh -L 2222:10.128.0.2:22 OpenSSH-rsa-import-101417@35.230.101.179
переподнял виртуалки, сейчас запущены
в тревисе ci прошел
юзер теперь appuser

2019-12-24 17:55 UTC, dsmamontov commented on README.md
> +ssh -L 2222:10.128.0.2:22 OpenSSH-rsa-import-101417@35.230.101.179
хотя нет, только билд проходит, насколько я понял..

2019-12-24 17:57 UTC, dsmamontov commented on README.md
> +ssh -L 2222:10.128.0.2:22 OpenSSH-rsa-import-101417@35.230.101.179
не совсем понимаю почему, правда, впн логинится, внутрений адрес internalhost пингуется

2019-12-24 18:04 UTC, dsmamontov commented on README.md
> +ssh -L 2222:10.128.0.2:22 OpenSSH-rsa-import-101417@35.230.101.179
после пуша запускается два пайплайна
первый проходит, второй нет.
судя по логу -- делают они то же самое.

Я не совсем понимаю почему их два, и что значит второй и как его пройти
Подскажите, пожалуйста)

2019-12-25 05:38 UTC, mrgreyves approved these changes
Здравствуйте!) Видимо фаза луны не та. Апрув!)

2019-12-25 06:12 UTC, merged

2019-12-25 15:24 UTC, dsmamontov commented
@mrgreyves добрый вечер!
как получить галочку на otus.ru к этому заданию?
после мёрджа не прилетела, до сих пор пожар)

2019-12-27 19:36 UTC, mrgreyves commented
В лс в слаке мне отпишитесь =)